- name: Wait for Tower to be available over HTTPS
  wait_for:
    port: 443
    delay: 20
  tags:
    - waittower

- name: Poll Tower over HTTPS
  uri:
    url: https://tower.lab.example.com
    validate_certs: no
  tags:
    - polltower
