---
- hosts:  all
  tasks:
  - name: Installing httpd
    yum:
      name: httpd
      state:  latest
    when: inventory_hostname in groups.webserver
    tags: apache

  - name: Restart httpd service
    service:
      name: httpd
      state:  restarted
    when: inventory_hostname in groups.webserver
    tags: apache

  - name:
    yum:
      name: postfix
      state:  present
    when: inventory_hostname in groups.mailserver
    tags: mail

  - name: restarting postfix service
    service:
      name: postfix
      state:  restarted
    when: inventory_hostname in groups.mailserver
    tags: mail
