---
- name: Installing apach HTTP related package
  yum:
    name: "{{ web_pkg }}"
    state: latest
  when: inventory_hostname in groups.web

- name: Publishing web content file
  copy:
    src: webcontent.html
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: 0644
  when: inventory_hostname in groups.web    


- name: Put webserver config. file
  template:
    src: web.j2
    dest: /etc/httpd/conf.d/web.conf
    owner: apache
    group: apache
    mode: 0644
  notify: restart_apache
  when: inventory_hostname in groups.web    


- name: Opening firewall port
  firewalld:
    port: "{{ web_port }}"
    state: enabled
    permanent: true
    immediate: true
  when: inventory_hostname in groups.web    
