#!/bin/bash
#
# Copyright 2016 Red Hat, Inc.
#
# NAME
#     demo-playbook - demo script for DO407 playbook demo
#
# SYNOPSIS
#     demo-playbook {setup|cleanup|reset}
#
#        setup   - create role as ~student on workstation
#        cleanup - remove changes applied to servera
#        reset   - same as cleanup + remove Ansible files on workstation
#
# DESCRIPTION
#     This script is used to setup the Ansible roles creation demo.
#
# CHANGELOG
#   * Wed May 18 2016 Chen Chang <cchang@redhat.com>
#   - changes to accomodate new dir structure
#   * Mon Apr 18 2016 Chen Chang <cchang@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
runuser='runuser student -c'
cd ~student

control_node='workstation'

targetw='workstation'
targeta='servera'
targetb='serverb'

lab_dir='/home/student/imp-playdemo'
ansible_cfg="${lab_dir}/ansible.cfg"
ansible_inventory="${lab_dir}/inventory"
client_playbook="${lab_dir}/ftpclient.yml"
server_playbook="${lab_dir}/ftpserver.yml"
log_dir="${lab_dir}/log"

ftpclient_playbook="${lab_dir}/ftpclient.yml"
ftpserver_playbook="${lab_dir}/ftpserver.yml"

declare -a valid_commands=(setup cleanup reset)

function lab_setup {

  control_node=${targetw}
  target=${targetw}

  # Check for lab prerequisites (perhaps a required package?).

  reqd_package='ansible'

  echo
  echo "Setting up ${control_node} for lab exercise work:"
  echo
  host_reachable ${control_node}

  pad " · ${reqd_package} package is installed on ${control_node}"
  if rpm -q --quiet ${reqd_package}
  then
    print_SUCCESS
  else
    if yum install -y ${reqd_package} &> /dev/null
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi

  pad ' · Creating working directory'

  cmd1="mkdir ${lab_dir}"

  if su - student -c "${ssh} ${target} '${cmd1}'" &> /dev/null
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad ' · Creating log directory'

  cmd1="mkdir ${log_dir}"

  if su - student -c "${ssh} ${target} '${cmd1}'" &> /dev/null
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad ' · Deploying Ansible inventory'

  file="${ansible_inventory}"
  cmd1="curl http://materials.example.com/grading/$file > $file"

  if su - student -c "${ssh} ${target} '${cmd1}'" &> /dev/null
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad ' · Deploying Ansible configuration'

  file="${ansible_cfg}"
  cmd1="curl http://materials.example.com/grading/$file > $file"

  if su - student -c "${ssh} ${target} '${cmd1}'" &> /dev/null
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad ' · Deploying client playbook'

  file="${client_playbook}"
  cmd1="curl http://materials.example.com/grading/$file > $file"

  if su - student -c "${ssh} ${target} '${cmd1}'" &> /dev/null
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad ' · Deploying server playbook'

  file="${server_playbook}"
  cmd1="curl http://materials.example.com/grading/$file > $file"

  if su - student -c "${ssh} ${target} '${cmd1}'" &> /dev/null
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  echo
}


function lab_cleanup {

  target=${targetw}

  echo
  echo "Cleaning up the lab on ${targetw}:"
  echo

  echo
}

function lab_reset {

  target=${targetw}

  echo
  echo "Resetting the lab on ${targetw}:"
  echo


  pad ' . Remove working directory'

  file="${lab_dir}"
  cmd1="rm -rf $file"

  ${ssh} ${target} ${cmd1} &> /dev/null
  print_SUCCESS

  echo

  pad ' . Remove ftp client'

  cmd1="yum remove -y lftp"

  ${ssh} ${target} ${cmd1} &> /dev/null
  print_SUCCESS

  echo

  pad ' . Remove ftp server'

  cmd1="yum remove -y vsftpd"

  ${ssh} ${targeta} ${cmd1} &> /dev/null
  print_SUCCESS


  pad ' . Restore firewall configuration'

  cmd1="firewall-cmd --delete-service=ftp --permanent"
  cmd2="firewall-cmd --reload"

  ${ssh} ${targeta} "${cmd1} && ${cmd2}" &> /dev/null
  print_SUCCESS

  echo
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
