#!/bin/bash
#
# Copyright 2017 Red Hat, Inc.
#
# NAME
#     lab-tower-webui - grading script for DO407
#
# SYNOPSIS
#     lab-tower-webui {setup|solve}
#
#        setup   - prepare the system for starting the lab
#        solve   - do the lab exercise for the student (may call setup)
#        (ONLY INCLUDE PROVIDED COMMANDS, REMOVE REST)
#
# DESCRIPTION
#     This script, based on singular argument, either does 
#     cleanup, or solve.
#
# CHANGELOG
#   * Tue May 16 2017 Chen Chang <cchang@redhat.com>
#   - Add lab_setup
#   * Mon Feb 27 2017 Chen Chang <cchang@redhat.com>
#   - Remove reference to lab_setup and lab_cleanup
#   * Tue Feb 21 2017 Chen Chang <cchang@redhat.com>
#   - change to use Ansible
#   * Fri Feb 17 2017 Chen Chang <cchang@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='tower'
projectdir='/root/ansible/DO407'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup solve)

function lab_setup {
  # Tower setup
  target='tower'
  print_header "Setting up ${target} for lab exercise work:"
  host_reachable ${target}

  pad " · Configure Demo Project on ${target}"
  cmd1="ansible-playbook -i ${projectdir}/inventories/admin/hosts ${projectdir}/localdemoproject.yml"
  if ${cmd1};
  then
    print_SUCCESS
  else
    print_FAIL
  fi
}


function lab_solve {
  lab_setup

  print_header "Solving the lab on ${target}:"

  pad ' · Launch Demo Job Template'
  tower-cli job launch -J 'Demo Job Template'

  if [ $? -eq 0 ];
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
