#!/bin/bash
#
# Copyright 2016 Red Hat, Inc.
#
# NAME
#     lab-managing-variables-inclusions - grading script for DO407
#
# SYNOPSIS
#     lab-managing-variables-inclusions {setup|grade|cleanup|solve|reset}
#
#        setup   - prepare the system for starting the lab
#        grade   - perform evaluation steps on the system
#        cleanup - perform post-lab cleanup (not comprehensive like reset)
#        solve   - do the lab exercise for the student (may call setup)
#        reset   - avoid resetting a machine (not preferred)
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     cleanup, reset, or solve for the lab for managing variable inclusions.
#
# CHANGELOG
#   * Thu May 26 2016 George Hacker <ghacker@redhat.com>
#   - incorporate newline '\n' in content of copy module
#   * Mon May 16 2016 George Hacker <ghacker@redhat.com>
#   - lab_cleanup no longer removes the student's work
#   - lab_setup provides student with a working config and inventory
#   - changed pkg parameter for yum module to name
#   * Tue May  3 2016 George Hacker <ghacker@redhat.com>
#   - changed print_SUCCESS calls to print_PASS in lab_grade
#   * Wed Apr 29 2016 Razique Mahroua <rmahroua@redhat.com>
#   - small updates to match the GE
#   * Wed Apr 13 2016 Razique Mahroua <rmahroua@redhat.com>
#   - small updates to match the GE
#   * Thur Mar 31 2016 Razique Mahroua <rmahroua@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'

control_node='workstation'

# Conditional to make the script compatible with the
# demo version.
if [[ ${lab_demo_mode} == "demo" ]]; then
  env="demo"
else
  env="dev"
fi

working_dir="/home/student/${env}-vars-inclusions"
ansible_cfg_file=${working_dir}/ansible.cfg
ansible_hst_file=${working_dir}/inventory
ansible_playbook_file=${working_dir}/playbook.yml
ansible_vars_dir=${working_dir}/vars
ansible_vars_file=${ansible_vars_dir}/variables.yml
ansible_tasks_dir=${working_dir}/tasks
ansible_tasks_file=${ansible_tasks_dir}/environment.yml
ansible_index_file=/var/www/html/index.html
ansible_user=devops
ansible_target=servera.lab.example.com
ansible_pkgs=(httpd firewalld)

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup grade cleanup solve reset)

function lab_setup {

  reqd_package='ansible'
  host_reachable ${control_node}
  echo
  echo "Setting up ${control_node} for lab exercise work:"
  echo

  pad " · ${reqd_package} package is installed on ${control_node}"
  if ! rpm -q --quiet ${reqd_package}
  then
    print_FAIL
  else
    print_SUCCESS
    if [[ ! -d ${working_dir} ]]
    then
      pad " · Creating the working directory"
      mkdir -p ${working_dir}
      cat << EOF >> ${ansible_cfg_file}
[defaults]
inventory   = ${ansible_hst_file##*/}
remote_user = ${ansible_user}

[privilege_escalation]
become      = true
EOF
      cat << EOF >> ${ansible_hst_file}
[webserver]
${ansible_target}
EOF
      chown -R student ${working_dir}
      print_SUCCESS
    fi
  fi

  echo
}

function lab_grade {

  host_reachable ${ansible_target}
  echo
  echo "Grading the student's work on ${control_node}:"
  echo

  pad " · Ensuring Ansible playbook is present"
  if stat ${ansible_playbook_file} &>/dev/null; then
    print_PASS
    pad " · Ensuring variables directory is present"
    if stat ${ansible_vars_dir} &>/dev/null; then
      print_PASS
      pad " · Ensuring variables file is present"
      if stat ${ansible_vars_file} &>/dev/null; then
        print_PASS
      else
        print_FAIL
      fi
      pad " · Ensuring tasks directory is present"
      if stat ${ansible_tasks_dir} &>/dev/null; then
        print_PASS
        pad " · Ensuring tasks file is present"
        if stat ${ansible_tasks_file} &>/dev/null; then
          print_PASS
          else
            print_FAIL
          fi
      else
        print_FAIL
      fi
    else
      print_FAIL
    fi
  else
    print_FAIL
  fi

  echo
  echo "Grading the student's work on ${control_node}:"
  echo

  echo " · Checking packages"
  for i in "${ansible_pkgs[@]}"; do
    pad "   · Checking $i"
    if ${ssh} ${ansible_target} rpm -q --quiet "$i"; then
      print_PASS
    else
      print_FAIL
    fi
  done

  echo " · Ensuring services are started"
  pad "   · Checking ${ansible_pkgs[0]}"
  if ${ssh} ${ansible_target} systemctl is-active ${ansible_pkgs[0]} &>/dev/null; then
    print_PASS
  else
    print_FAIL
  fi
  pad "   · Checking ${ansible_pkgs[1]}"
  if ${ssh} ${ansible_target} systemctl is-active ${ansible_pkgs[1]} &>/dev/null; then
    print_PASS
  else
    print_FAIL
  fi

  pad " · Ensuring the web server is reachable"
  if curl -s -I http://${ansible_target} | grep -q 200; then
    print_PASS
  else
    print_FAIL
  fi

  # Overall grade
  echo
  pad 'Overall lab grade'
  if [[ ${fail_count} -eq 0 ]]
  then
    print_PASS
  else
    print_FAIL
  fi

  echo
}

function lab_cleanup {

  host_reachable ${ansible_target}
  echo
  echo "Cleaning up the lab on ${ansible_target}:"
  echo

  pad " · Removing index.html"
  if ${ssh} ${ansible_target} rm -rf ${ansible_index_file} &>/dev/null; then
    print_SUCCESS
  else
    print_FAIL
  fi

  echo " · Removing packages"
  for i in "${ansible_pkgs[@]}"; do
    pad "   · Removing $i"
    if ${ssh} ${ansible_target} yum -y remove "$i" &>/dev/null; then
      print_SUCCESS
    else
      print_FAIL
    fi
  done

  echo
}


function lab_solve {

  lab_reset
  lab_setup

  echo
  echo "Solving the lab on ${control_node}:"
  echo

  pad " · Creating tasks directory"
  if mkdir ${ansible_tasks_dir}; then
    print_SUCCESS
    pad " · Creating tasks file"
    cat > ${ansible_tasks_file} << EOF
---
  - name: Install and start the web server
    yum:
      name: "{{ package }}"
      state: latest
  - name: Start the service
    service:
      name: "{{ service }}"
      state: "{{ svc_state }}"
EOF
     if stat ${ansible_tasks_file} &>/dev/null; then
        print_SUCCESS
      else
        print_FAIL
      fi
    else
      print_FAIL
    fi

    pad " · Creating vars directory"
    if mkdir ${ansible_vars_dir}; then
      print_SUCCESS
      pad " · Creating vars file"
      cat > ${ansible_vars_file} << EOF
---
firewall_pkg: firewalld
EOF
      if stat ${ansible_vars_file} &>/dev/null; then
        print_SUCCESS
      else
        print_FAIL
      fi
    else
      print_FAIL
    fi

  pad " · Creating ${ansible_playbook_file##*/}"
  cat > ${ansible_playbook_file} << EOF
---
- hosts: webserver
  vars:
    rule: http
  tasks:
    - name: Include the variables from the YAML file
      include_vars: vars/variables.yml

    - name: Include the environment file and set the variables
      include: tasks/environment.yml
      vars:
        package: httpd
        service: httpd
        svc_state: started

    - name: Install the firewall
      yum:
        name: "{{ firewall_pkg }}"
        state: latest

    - name: Start the firewall
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Open the port for {{ rule }}
      firewalld:
        service: "{{ rule }}"
        immediate: true
        permanent: true
        state: enabled

    - name: Create index.html
      copy:
        content: "{{ ansible_fqdn }} has been customized using Ansible on the {{ ansible_date_time.date }}\n"
        dest: /var/www/html/index.html
EOF
  if stat ${ansible_playbook_file} &>/dev/null; then
    print_SUCCESS
  else
    print_FAIL
  fi

  chown -R student ${working_dir}

  cd ${working_dir}
  pad " · Running the playbook"
  if ansible-playbook -i ${ansible_hst_file} ${ansible_playbook_file} &>/dev/null; then
    print_SUCCESS
  else
    print_FAIL
  fi

  echo
}

function lab_reset {

  lab_cleanup

  echo "Resetting the lab on ${control_node}:"
  echo

  pad " · Removing the working directory"
  if rm -rf ${working_dir}; then
    print_SUCCESS
  else
    print_FAIL
  fi

  echo
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
