#!/bin/bash
#
# Copyright 2016 Red Hat, Inc.
#
# NAME
#     lab-task-control-failures - grading script for DO407
#
# SYNOPSIS
#     lab-task-control-failures {setup|grade|cleanup|solve|reset}
#
#        setup   - prepare the system for starting the lab
#        grade   - perform evaluation steps on the system
#        cleanup - perform post-lab cleanup (not comprehensive like reset)
#        solve   - do the lab exercise for the student (may call setup)
#        reset   - avoid resetting a machine (not preferred)
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     cleanup, reset, or solve for the lab for managing failures.
#
# CHANGELOG
#   * Tue Jun 20 2017 Artur Glogowski <aglogows@redhat.com>
#   - lab_cleanup fixed
#   * Wed May 18 2016 George Hacker <ghacker@redhat.com>
#   - lab_cleanup no longer removes the student's work
#   - lab_setup provides student with a working config and inventory
#   - changed pkg parameter for yum module to name
#   * Tue May  3 2016 George Hacker <ghacker@redhat.com>
#   - changed print_SUCCESS calls to print_PASS in lab_grade
#   * Wed Apr 20 2016 Razique Mahroua <rmahroua@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
runuser='runuser student -c'

control_node='workstation'

# Conditional to make the script compatible with the
# demo version.
if [[ ${lab_demo_mode} == "demo" ]]; then
  env="demo"
else
  env="dev"
fi

working_dir="/home/student/${env}-failures"
ansible_cfg_file=${working_dir}/ansible.cfg
ansible_hst_file=${working_dir}/inventory
ansible_playbook_file=${working_dir}/playbook.yml
ansible_db_file=http://materials.example.com/task_control
ansible_user=devops
ansible_target=servera.lab.example.com
ansible_pkg=mariadb-server

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup grade cleanup solve reset)

function lab_setup {

  reqd_package='ansible'
  host_reachable ${control_node}
  echo
  echo "Setting up ${control_node} for lab exercise work:"
  echo

  pad " · ${reqd_package} package is installed on ${control_node}"
  if ! rpm -q --quiet ${reqd_package}
  then
    print_FAIL
  else
    print_SUCCESS
    if [[ ! -d ${working_dir} ]]
    then
      pad " · Creating the working directory"
      mkdir -p ${working_dir}
      cat << EOF >> ${ansible_cfg_file}
[defaults]
inventory   = ${ansible_hst_file##*/}
remote_user = ${ansible_user}

[privilege_escalation]
become      = true
EOF
      cat << EOF >> ${ansible_hst_file}
[databases]
${ansible_target}
EOF
      chown -R student:student ${working_dir}
      print_SUCCESS
    fi
  fi

  echo
}

function lab_grade {

  host_reachable ${ansible_target}
  echo
  echo "Grading the student's work on ${control_node}:"
  echo

  pad " · Ensuring playbook is present"
  if [[ -f ${ansible_playbook_file} ]]
  then
    print_PASS
  else
    print_FAIL
  fi

  echo
  echo "Grading the student's work on ${ansible_target}:"
  echo

  pad " · Ensuring ${ansible_pkg} has been installed"
  if ${ssh} ${ansible_target} rpm -q "${ansible_pkg}" &> /dev/null
  then
    print_PASS
  else
    print_FAIL
  fi

  # Overall grade
  echo
  pad 'Overall lab grade'
  if [[ ${fail_count} -eq 0 ]]
  then
    print_PASS
  else
    print_FAIL
  fi

  echo
}

function lab_cleanup {

  host_reachable ${ansible_target}
  
  echo
  echo "Cleaning up the lab on ${ansible_target}:"
  echo

  pad " · Removing ${ansible_pkg}"
  if ${ssh} ${ansible_target} yum -y remove "${ansible_pkg}" &>/dev/null; then
    print_SUCCESS
  else
    print_FAIL
  fi

  
}


function lab_solve {

  lab_reset
  lab_setup

  echo
  echo "Solving the lab on ${control_node}:"
  echo

  pad " · Creating the playbook"
  cat > ${ansible_playbook_file} << EOF
---
- hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: Install {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: latest

    - name: Install {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: latest
EOF

  if [[ -f ${ansible_playbook_file} ]]; then
    chown -R student:student ${working_dir} && print_SUCCESS
    pad " · Ensuring the play fails"
    if ! ${runuser} "cd ${working_dir} && ansible-playbook ${ansible_playbook_file}" &>/dev/null; then
      print_SUCCESS
    else
      print_FAIL
    fi
  else
    print_FAIL
  fi

  pad " · Updating the playbook"
  cat > ${ansible_playbook_file} << EOF
---
- hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: Install {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: latest
      ignore_errors: yes

    - name: Install {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: latest
EOF

  if [[ -f ${ansible_playbook_file} ]]; then
    chown -R student:student ${working_dir} && print_SUCCESS
    pad " · Running the playbook"
    if ${runuser} "ansible-playbook ${ansible_playbook_file}" &>/dev/null; then
      print_SUCCESS
    else
      print_FAIL
    fi
  else
    print_FAIL
  fi

  pad " · Updating the playbook"
  cat > ${ansible_playbook_file} << EOF
---
- hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: Check {{ web_package }} installation status
      command: yum list installed {{ web_package }}
      register: command_result
      ignore_errors: yes

    - name: Install {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: latest
      ignore_errors: yes

    - name: Install {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: latest
EOF

 if [[ -f ${ansible_playbook_file} ]]; then
    chown -R student:student ${working_dir} && print_SUCCESS
    pad " · Running the playbook"
    if ${runuser} "ansible-playbook ${ansible_playbook_file}" &>/dev/null; then
      print_SUCCESS
    else
      print_FAIL
    fi
  else
    print_FAIL
  fi

  pad " · Updating the playbook"
  cat > ${ansible_playbook_file} << EOF
---
- hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: Check {{ web_package }} installation status
      command: yum list "{{ web_package }}"
      register: command_result
      ignore_errors: yes

    - name: Install {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: latest
      ignore_errors: yes

    - name: Install {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: latest
      when: "'Error' in command_result.stdout"
EOF

 if [[ -f ${ansible_playbook_file} ]]; then
    chown -R student:student ${working_dir} && print_SUCCESS
    pad " · Removing ${ansible_pkg}"
    if ssh -tt devops@${ansible_target} "sudo yum -y remove ${ansible_pkg}" &>/dev/null; then
      print_SUCCESS
    else
      print_FAIL
    fi

    pad " · Running the playbook"
    if ${runuser} "cd ${working_dir} && ansible-playbook ${ansible_playbook_file}" &>/dev/null; then
      print_SUCCESS
    else
      print_FAIL
    fi
  else
    print_FAIL
  fi

  pad " · Updating the playbook"
  cat > ${ansible_playbook_file} << EOF
---
- hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: Check {{ web_package }} installation status
      command: yum list "{{ web_package }}"
      register: command_result
      ignore_errors: yes

    - name: Install {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: latest
      ignore_errors: yes

    - name: Install {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: latest
      # when: "'Error' in command_result.stdout"
      changed_when: "command_result.rc == 1"
EOF

  if [[ -f ${ansible_playbook_file} ]]; then
    chown -R student:student ${working_dir} && print_SUCCESS
    pad " · Running the playbook"
    if ${runuser} "cd ${working_dir} && ansible-playbook ${ansible_playbook_file}" &>/dev/null; then
      print_SUCCESS
    else
      print_FAIL
    fi

    pad " · Running the playbook"
    if ${runuser} "cd ${working_dir} && ansible-playbook ${ansible_playbook_file}" &>/dev/null; then
      print_SUCCESS
    else
      print_FAIL
    fi
  else
    print_FAIL
  fi

  pad " · Updating the playbook"
  cat > ${ansible_playbook_file} << EOF
---
- hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - block:
      - name: Check {{ web_package }} installation status
        command: yum list "{{ web_package }}"
        register: command_result

      - name: Install {{ web_package }} package
        yum:
          name: "{{ web_package }}"
          state: latest

      rescue:
        - name: Install {{ db_package }} package
          yum:
            name: "{{ db_package }}"
            state: latest

      always:
        - name: Start {{ db_service }} service
          service:
            name: "{{ db_service }}"
            state: started
EOF

  if [[ -f ${ansible_playbook_file} ]]; then
    chown -R student:student ${working_dir} && print_SUCCESS
    pad " · Removing ${ansible_pkg}"
    if ssh -tt devops@${ansible_target} "sudo yum -y remove ${ansible_pkg}" &>/dev/null; then
      print_SUCCESS
    else
      print_FAIL
    fi

    pad " · Running the playbook"
    if ${runuser} "cd ${working_dir} && ansible-playbook ${ansible_playbook_file}" &>/dev/null; then
      print_SUCCESS
    else
      print_FAIL
    fi
  else
    print_FAIL
  fi

  echo
}

function lab_reset {

  lab_cleanup

  echo "Resetting the lab on ${control_node}:"
  echo

  pad " · Removing the working directory"
  if rm -rf ${working_dir}; then
    print_SUCCESS
  else
    print_FAIL
  fi

  echo
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
