#!/bin/bash
#
# Copyright 2016 Red Hat, Inc.
#
# NAME
#     lab-troubleshoot-managedhosts - grading script for DO407 Troubleshooting Ansible Managed Hosts Guided Exercise (Chapter 10)
#
# SYNOPSIS
#     lab-troubleshoot-managedhosts {setup}
#
#        setup   - prepare the system for starting the lab
#
# DESCRIPTION
#     This script install the ansible and telnet packages 
#     in workstation and creates the working directory
#
# CHANGELOG
#   * Wed Jun  8 2016 Chen Chang <cchang@redhat.com>
#   - Add postfix install to lab_setup
#   * Tue Apr 19 2016 Adolfo Vazquez <avr@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
ssh='ssh -o StrictHostKeyChecking=no'
scp='scp -q'
target='workstation'
targeta='servera'
# Conditional to make the script compatible with the
# demo version.
if [[ ${lab_demo_mode} == "demo" ]]; then
  env="demo"
else
  env="dev"
fi

working_dir="/home/student/troubleshooting"
ansible_inventory_file=inventory
ansible_playbook_file=mailrelay.yml
ansible_j2_file=postfix-relay-main.conf.j2
ansible_user=devops
ansible_target=servera.lab.example.com
LOG=/dev/null

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup)

function lab_setup {
  reqd_package='ansible'
  telnet_package='telnet'
  postfix_package='postfix'

  echo
  echo "Setting up ${target} for lab exercise work:"
  echo
  host_reachable ${target}


  if ! rpm -q --quiet ${reqd_package}
  then
    pad " . Installing ${reqd_package} package on ${target}"
    if yum -y install ansible &>/dev/null; then
        print_SUCCESS
    else
        print_FAIL
    fi
  fi

  if ! rpm -q --quiet ${telnet_package}
  then
    pad " . Installing ${telnet_package} package on ${target}"
    if yum -y install telnet &>/dev/null; then
        print_SUCCESS
    else
        print_FAIL
    fi
  fi

    pad " . Checking ${postfix_package} package on ${targeta}"
    if ${ssh} ${targeta} 'rpm -q postfix' ; then
      ${ssh} ${targeta} 'rpm -e postfix' && print_SUCCESS
    else
        print_SUCCESS
    fi

  pad " . Creating the working directory"
  mkdir -p ${working_dir}
  chown -R student. ${working_dir}
  print_SUCCESS

  pad " . Downloading ${ansible_inventory_file}"
  if wget http://materials.example.com/troubleshooting/${ansible_inventory_file} -O ${working_dir}/${ansible_inventory_file} &>/dev/null; then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " . Downloading ${ansible_playbook_file}"
  if wget http://materials.example.com/troubleshooting/${ansible_playbook_file} -O ${working_dir}/${ansible_playbook_file} &>/dev/null; then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " . Downloading ${ansible_j2_file}"
  if wget http://materials.example.com/troubleshooting/${ansible_j2_file} -O ${working_dir}/${ansible_j2_file} &>/dev/null; then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " . Changing permissions to the working directory"
  chown -R student. ${working_dir}
  print_SUCCESS
}

function lab_grade {

  echo
  echo "Grading the student's work on ${target}:"
  echo
  host_reachable ${target}

  # Overall grade
  echo
  pad 'Overall lab grade'
  if [[ ${fail_count} -eq 0 ]]
  then
    print_PASS
  else
    print_FAIL
  fi

  echo
}

function lab_cleanup {

  echo
  echo "Cleaning up the lab on ${target}:"
  echo
  host_reachable ${target}

  print_SUCCESS

}


function lab_solve {

  lab_reset
  lab_setup

  echo
  echo "Solving the lab on ${target}:"
  echo

  print_SUCCESS

}

function lab_reset {

  echo
  echo "Resetting the lab on ${target}:"
  echo
  host_reachable ${target}

  print_SUCCESS

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
