---
# tasks file for ansible-vsftpd
- name: Packages are installed
  yum:
    name: '{{ vsftpd_packages }}'
    state: installed

- name: Ensure service is started
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items: '{{ vsftpd_service }}'

- name: Configuration file is installed
  template:
    src: vsftpd.conf.j2
    dest: '{{ vsftpd_config_file }}'
    owner: root
    group: root
    mode: '0600'
    setype: etc_t
  notify: restart vsftpd

- name: firewalld is installed
  yum: 
    name: firewalld
    state: present

- name: firewalld is started and enabled
  service: 
    name: firewalld
    state: started
    enabled: yes

- name: Open ftp port in firewall
  firewalld:
    service: ftp
    permanent: true
    state: enabled
    immediate: yes

